databases:
  - name: real-rent-car-db
    databaseName: real_rent_car
    user: admin
    plan: free
    region: oregon

services:
  - type: web
    name: real-rent-car
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: real-rent-car-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: real-rent-car-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: real-rent-car-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: real-rent-car-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: real-rent-car-db
          property: password
